-- ============================================================
-- PSIREAL - SMI + BIBLIOTECA TE - REVISAO CODEX
-- Execute apos psireal_supabase_migration_final.sql
-- ============================================================

create table if not exists public.respostas_smi (
  id bigint generated by default as identity primary key,
  psi_user_id uuid not null references public.psis(user_id) on delete cascade,
  patient_link_id uuid references public.patient_links(id) on delete set null,
  paciente_nome text not null,
  paciente_nascimento date,
  respostas jsonb not null,
  scores_modos jsonb,
  scores_dominios jsonb,
  modo_predominante text,
  alertas_clinicos jsonb,
  cruzamento_ysq jsonb,
  notas_psi text,
  status text not null default 'novo',
  psi_id text,
  criado_em timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists respostas_smi_psi_user_id_idx
  on public.respostas_smi (psi_user_id);
create index if not exists respostas_smi_created_at_idx
  on public.respostas_smi (created_at desc);

create or replace function public.sync_respostas_smi_legado()
returns trigger
language plpgsql
set search_path = public
as $function$
begin
  if NEW.criado_em is null then
    NEW.criado_em := NEW.created_at;
  end if;
  if NEW.psi_id is null and NEW.psi_user_id is not null then
    select psi_id into NEW.psi_id
    from public.psis
    where user_id = NEW.psi_user_id;
  end if;
  return NEW;
end;
$function$;

drop trigger if exists trg_sync_smi_legado on public.respostas_smi;
create trigger trg_sync_smi_legado
before insert or update on public.respostas_smi
for each row execute function public.sync_respostas_smi_legado();

alter table public.respostas_smi enable row level security;
grant select, update on public.respostas_smi to authenticated;

drop policy if exists "smi_select_own" on public.respostas_smi;
create policy "smi_select_own"
on public.respostas_smi for select to authenticated
using (psi_user_id = auth.uid());

drop policy if exists "smi_update_own" on public.respostas_smi;
create policy "smi_update_own"
on public.respostas_smi for update to authenticated
using (psi_user_id = auth.uid())
with check (psi_user_id = auth.uid());

create table if not exists public.biblioteca_te (
  id bigint generated by default as identity primary key,
  ref_id text unique not null,
  categoria text not null,
  cor text not null,
  autores text not null,
  ano integer not null,
  titulo text not null,
  subtitulo text,
  tipo text default 'livro',
  periodico text,
  editora text,
  local_pub text,
  volume text,
  numero text,
  paginas text,
  doi text,
  instituicao text,
  resumo text not null,
  tags text[],
  destaque boolean default false,
  created_at timestamptz not null default now()
);

alter table public.biblioteca_te enable row level security;
grant select on public.biblioteca_te to authenticated;

drop policy if exists "biblioteca_select_all" on public.biblioteca_te;
create policy "biblioteca_select_all"
on public.biblioteca_te for select to authenticated
using (true);

create table if not exists public.regras_ativacao (
  id bigint generated by default as identity primary key,
  dominio_ysq text not null,
  esquemas text[] not null,
  modos_primarios text[] not null,
  modos_secundarios text[],
  descricao text not null,
  implicacao_clinica text,
  nivel_alerta text not null default 'moderado',
  fonte text default 'Young, Klosko & Weishaar (2003)',
  created_at timestamptz not null default now()
);

create unique index if not exists regras_ativacao_dominio_idx
  on public.regras_ativacao (dominio_ysq);

alter table public.regras_ativacao enable row level security;
grant select on public.regras_ativacao to authenticated;

drop policy if exists "regras_select_all" on public.regras_ativacao;
create policy "regras_select_all"
on public.regras_ativacao for select to authenticated
using (true);

create or replace function public.submit_smi_response(
  p_token uuid,
  p_patient_name text,
  p_patient_birth date,
  p_respostas jsonb,
  p_scores_modos jsonb,
  p_scores_dominios jsonb,
  p_modo_predominante text,
  p_alertas_clinicos jsonb default null
)
returns void
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_link public.patient_links%rowtype;
  v_psi_id text;
begin
  select *
  into v_link
  from public.patient_links
  where token = p_token
    and instrumento = 'SMI'
    and status = 'ativo'
    and (expires_at is null or expires_at > now())
  limit 1;

  if v_link.id is null then
    raise exception 'invalid or expired link';
  end if;

  select psi_id
  into v_psi_id
  from public.psis
  where user_id = v_link.psi_user_id;

  insert into public.respostas_smi (
    psi_user_id,
    patient_link_id,
    paciente_nome,
    paciente_nascimento,
    respostas,
    scores_modos,
    scores_dominios,
    modo_predominante,
    alertas_clinicos,
    psi_id,
    criado_em,
    status,
    created_at
  ) values (
    v_link.psi_user_id,
    v_link.id,
    coalesce(nullif(trim(p_patient_name), ''), v_link.patient_name),
    coalesce(p_patient_birth, v_link.patient_birth),
    p_respostas,
    p_scores_modos,
    p_scores_dominios,
    p_modo_predominante,
    p_alertas_clinicos,
    v_psi_id,
    now(),
    'novo',
    now()
  );

  update public.patient_links
  set status = 'respondido'
  where id = v_link.id;
end;
$function$;

revoke all on function public.submit_smi_response(uuid, text, date, jsonb, jsonb, jsonb, text, jsonb) from public;
grant execute on function public.submit_smi_response(uuid, text, date, jsonb, jsonb, jsonb, text, jsonb)
  to anon, authenticated;
