-- PsiReal Hub - SQL migration final v2026-05-17
create extension if not exists pgcrypto;

create table if not exists public.psis (
  user_id uuid primary key references auth.users(id) on delete cascade,
  psi_id text unique not null,
  nome text not null,
  email text unique not null,
  whatsapp text,
  plano text not null default 'mensal',
  ativa boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.patient_links (
  id uuid primary key default gen_random_uuid(),
  token uuid unique not null default gen_random_uuid(),
  psi_user_id uuid not null references public.psis(user_id) on delete cascade,
  patient_name text not null,
  patient_birth date,
  instrumento text not null,
  status text not null default 'ativo'
    check (status in ('ativo','respondido','revogado','expirado')),
  expires_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists patient_links_psi_user_id_idx on public.patient_links (psi_user_id);
create index if not exists patient_links_token_idx on public.patient_links (token);

create table if not exists public.respostas_clinicas (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now()
);

alter table public.respostas_clinicas
  add column if not exists psi_user_id uuid references public.psis(user_id) on delete cascade,
  add column if not exists patient_link_id uuid references public.patient_links(id) on delete set null,
  add column if not exists instrumento text,
  add column if not exists respostas jsonb,
  add column if not exists scores jsonb,
  add column if not exists score_total numeric,
  add column if not exists status text not null default 'novo',
  add column if not exists notas_psi text,
  add column if not exists paciente_nome text,
  add column if not exists paciente_nascimento date,
  add column if not exists psi_id text,
  add column if not exists formulario text,
  add column if not exists criado_em timestamptz;

create index if not exists respostas_psi_user_id_idx on public.respostas_clinicas (psi_user_id);
create index if not exists respostas_psi_id_idx on public.respostas_clinicas (psi_id);
create index if not exists respostas_formulario_idx on public.respostas_clinicas (formulario);
create index if not exists respostas_criado_em_idx on public.respostas_clinicas (criado_em desc);
create index if not exists respostas_created_at_idx on public.respostas_clinicas (created_at desc);

create or replace function public.sync_respostas_legado()
returns trigger language plpgsql as $$
begin
  if new.instrumento is not null and new.formulario is null then
    new.formulario := new.instrumento;
  end if;
  if new.criado_em is null then
    new.criado_em := new.created_at;
  end if;
  if new.psi_id is null and new.psi_user_id is not null then
    select psi_id into new.psi_id from public.psis where user_id = new.psi_user_id;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_sync_respostas_legado on public.respostas_clinicas;
create trigger trg_sync_respostas_legado
before insert or update on public.respostas_clinicas
for each row execute function public.sync_respostas_legado();

create table if not exists public.contatos (
  id bigint generated by default as identity primary key,
  nome text not null,
  whatsapp text not null,
  servico text not null,
  mensagem text,
  pagina text,
  status text not null default 'novo',
  notas text,
  created_at timestamptz not null default now()
);

create index if not exists contatos_created_at_idx on public.contatos (created_at desc);
create index if not exists contatos_status_idx on public.contatos (status);

alter table public.psis enable row level security;
alter table public.admin_users enable row level security;
alter table public.patient_links enable row level security;
alter table public.respostas_clinicas enable row level security;
alter table public.contatos enable row level security;

revoke all on public.psis from anon;
revoke all on public.admin_users from anon;
revoke all on public.patient_links from anon;
revoke all on public.respostas_clinicas from anon;

grant usage on schema public to anon, authenticated;
grant select on public.psis to authenticated;
grant select on public.admin_users to authenticated;
grant select, insert, update on public.patient_links to authenticated;
grant select, update on public.respostas_clinicas to authenticated;
grant insert on public.contatos to anon, authenticated;
grant update on public.contatos to authenticated;
grant select on public.contatos to authenticated;

drop policy if exists "psis_select_own" on public.psis;
create policy "psis_select_own"
on public.psis for select to authenticated
using (user_id = auth.uid());

drop policy if exists "admin_users_select_self" on public.admin_users;
create policy "admin_users_select_self"
on public.admin_users for select to authenticated
using (user_id = auth.uid());

drop policy if exists "patient_links_select_own" on public.patient_links;
create policy "patient_links_select_own"
on public.patient_links for select to authenticated
using (psi_user_id = auth.uid());

drop policy if exists "patient_links_insert_own" on public.patient_links;
create policy "patient_links_insert_own"
on public.patient_links for insert to authenticated
with check (psi_user_id = auth.uid());

drop policy if exists "patient_links_update_own" on public.patient_links;
create policy "patient_links_update_own"
on public.patient_links for update to authenticated
using (psi_user_id = auth.uid())
with check (psi_user_id = auth.uid());

drop policy if exists "responses_select_own" on public.respostas_clinicas;
create policy "responses_select_own"
on public.respostas_clinicas for select to authenticated
using (psi_user_id = auth.uid());

drop policy if exists "responses_update_own" on public.respostas_clinicas;
create policy "responses_update_own"
on public.respostas_clinicas for update to authenticated
using (psi_user_id = auth.uid())
with check (psi_user_id = auth.uid());

drop policy if exists "admin_select_all_responses" on public.respostas_clinicas;
create policy "admin_select_all_responses"
on public.respostas_clinicas for select to authenticated
using (
  exists (
    select 1
    from public.admin_users
    where admin_users.user_id = auth.uid()
  )
);

drop policy if exists "admin_update_all_responses" on public.respostas_clinicas;
create policy "admin_update_all_responses"
on public.respostas_clinicas for update to authenticated
using (
  exists (
    select 1
    from public.admin_users
    where admin_users.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.admin_users
    where admin_users.user_id = auth.uid()
  )
);

drop policy if exists "public_insert_contatos" on public.contatos;
create policy "public_insert_contatos"
on public.contatos for insert to anon, authenticated
with check (
  length(trim(nome)) > 0
  and length(trim(whatsapp)) > 0
  and length(trim(servico)) > 0
  and status = 'novo'
);

drop policy if exists "admin_select_contatos" on public.contatos;
create policy "admin_select_contatos"
on public.contatos for select to authenticated
using (
  exists (
    select 1
    from public.admin_users
    where admin_users.user_id = auth.uid()
  )
);

drop policy if exists "admin_update_contatos" on public.contatos;
create policy "admin_update_contatos"
on public.contatos for update to authenticated
using (
  exists (
    select 1
    from public.admin_users
    where admin_users.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.admin_users
    where admin_users.user_id = auth.uid()
  )
);

create or replace function public.create_patient_link(
  p_patient_name text,
  p_patient_birth date,
  p_instrumento text,
  p_expires_at timestamptz default null
)
returns table(token uuid, patient_name text, instrumento text)
language plpgsql security definer set search_path = public
as $$
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  if not exists (select 1 from public.psis where user_id = auth.uid() and ativa = true) then
    raise exception 'inactive psychologist';
  end if;
  return query
  insert into public.patient_links (psi_user_id, patient_name, patient_birth, instrumento, expires_at)
  values (auth.uid(), trim(p_patient_name), p_patient_birth, p_instrumento, p_expires_at)
  returning patient_links.token, patient_links.patient_name, patient_links.instrumento;
end;
$$;

revoke all on function public.create_patient_link(text, date, text, timestamptz) from public;
grant execute on function public.create_patient_link(text, date, text, timestamptz) to authenticated;

create or replace function public.submit_patient_response(
  p_token uuid,
  p_patient_name text,
  p_patient_birth date,
  p_instrumento text,
  p_respostas jsonb,
  p_scores jsonb,
  p_score_total numeric
)
returns void language plpgsql security definer set search_path = public
as $$
declare
  v_link public.patient_links%rowtype;
  v_psi_id text;
begin
  select * into v_link
  from public.patient_links
  where token = p_token
    and status = 'ativo'
    and (expires_at is null or expires_at > now())
  limit 1;

  if v_link.id is null then raise exception 'invalid or expired link'; end if;
  if v_link.instrumento <> p_instrumento then raise exception 'instrument mismatch'; end if;

  select psi_id into v_psi_id from public.psis where user_id = v_link.psi_user_id;

  insert into public.respostas_clinicas (
    psi_user_id, patient_link_id,
    paciente_nome, paciente_nascimento,
    instrumento, formulario,
    respostas, scores, score_total,
    psi_id, criado_em, status, created_at
  ) values (
    v_link.psi_user_id, v_link.id,
    coalesce(nullif(trim(p_patient_name), ''), v_link.patient_name),
    coalesce(p_patient_birth, v_link.patient_birth),
    p_instrumento, p_instrumento,
    p_respostas, p_scores, p_score_total,
    v_psi_id, now(), 'novo', now()
  );

  update public.patient_links set status = 'respondido' where id = v_link.id;
end;
$$;

revoke all on function public.submit_patient_response(uuid, text, date, text, jsonb, jsonb, numeric) from public;
grant execute on function public.submit_patient_response(uuid, text, date, text, jsonb, jsonb, numeric) to anon, authenticated;
