-- PsiReal TCC - pacientes: status e exclusao segura por psicologa
-- Rode este arquivo no Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.pacientes (
  id bigint generated by default as identity primary key,
  psi_user_id uuid references public.psis(user_id) on delete cascade,
  nome text not null,
  whatsapp text,
  status text not null default 'ativo',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.pacientes
  add column if not exists psi_user_id uuid references public.psis(user_id) on delete cascade,
  add column if not exists nome text,
  add column if not exists whatsapp text,
  add column if not exists status text default 'ativo',
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

create unique index if not exists pacientes_psi_nome_lower_uidx
on public.pacientes (psi_user_id, lower(nome));

create index if not exists pacientes_psi_user_id_idx
on public.pacientes (psi_user_id);

alter table public.pacientes enable row level security;

grant select, insert, update, delete on public.pacientes to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists "pacientes_select_own" on public.pacientes;
create policy "pacientes_select_own"
on public.pacientes for select to authenticated
using (psi_user_id = auth.uid());

drop policy if exists "pacientes_insert_own" on public.pacientes;
create policy "pacientes_insert_own"
on public.pacientes for insert to authenticated
with check (psi_user_id = auth.uid());

drop policy if exists "pacientes_update_own" on public.pacientes;
create policy "pacientes_update_own"
on public.pacientes for update to authenticated
using (psi_user_id = auth.uid())
with check (psi_user_id = auth.uid());

drop policy if exists "pacientes_delete_own" on public.pacientes;
create policy "pacientes_delete_own"
on public.pacientes for delete to authenticated
using (psi_user_id = auth.uid());

create or replace function public.upsert_patient_status(
  p_patient_name text,
  p_status text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id bigint;
  v_name text;
begin
  if auth.uid() is null then
    raise exception 'authentication required';
  end if;

  v_name := trim(coalesce(p_patient_name, ''));
  if v_name = '' then
    raise exception 'patient name required';
  end if;

  if p_status not in ('ativo', 'pendente', 'pausa', 'inativo') then
    raise exception 'invalid status';
  end if;

  select id into v_id
  from public.pacientes
  where psi_user_id = auth.uid()
    and lower(nome) = lower(v_name)
  limit 1;

  if v_id is null then
    insert into public.pacientes (psi_user_id, nome, status, updated_at)
    values (auth.uid(), v_name, p_status, now());
  else
    update public.pacientes
    set status = p_status,
        updated_at = now()
    where id = v_id
      and psi_user_id = auth.uid();
  end if;
end;
$$;

revoke all on function public.upsert_patient_status(text, text) from public;
grant execute on function public.upsert_patient_status(text, text) to authenticated;

create or replace function public.delete_patient_data(
  p_patient_name text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_name text;
begin
  if auth.uid() is null then
    raise exception 'authentication required';
  end if;

  v_name := trim(coalesce(p_patient_name, ''));
  if v_name = '' then
    raise exception 'patient name required';
  end if;

  delete from public.patient_links
  where psi_user_id = auth.uid()
    and patient_name = v_name;

  delete from public.respostas_clinicas
  where psi_user_id = auth.uid()
    and paciente_nome = v_name;

  delete from public.pacientes
  where psi_user_id = auth.uid()
    and lower(nome) = lower(v_name);
end;
$$;

revoke all on function public.delete_patient_data(text) from public;
grant execute on function public.delete_patient_data(text) to authenticated;
