-- Public contact forms from the Psi Real website.
create table if not exists public.contatos (
  id bigint generated by default as identity primary key,
  nome text not null,
  whatsapp text not null,
  servico text not null,
  mensagem text,
  pagina text,
  status text not null default 'novo',
  created_at timestamptz not null default now()
);

alter table public.contatos enable row level security;

grant usage on schema public to anon, authenticated;
grant insert on public.contatos to anon, authenticated;

drop policy if exists "public_insert_contatos" on public.contatos;
create policy "public_insert_contatos"
on public.contatos
for insert
to anon, authenticated
with check (
  length(trim(nome)) > 0
  and length(trim(whatsapp)) > 0
  and length(trim(servico)) > 0
  and status = 'novo'
);

create index if not exists contatos_created_at_idx
on public.contatos (created_at desc);
