-- ============================================================
-- PSIREAL - MAPEAMENTO DE ATIVACAO DO TERAPEUTA - REVISAO CODEX
-- Execute apos:
-- 1. psireal_supabase_migration_final.sql
-- 2. psireal_smi_supabase.sql
-- ============================================================

create table if not exists public.perfil_psi_clinico (
  id bigint generated by default as identity primary key,
  psi_user_id uuid not null references public.psis(user_id) on delete cascade,
  ysq_scores jsonb not null default '{}',
  smi_scores jsonb not null default '{}',
  preenchido_em timestamptz not null default now(),
  versao_ysq text default 'YSQ-S3',
  versao_smi text default 'SMI-1.1',
  notas_pessoais text,
  n_preenchimentos integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists perfil_psi_clinico_psi_user_id_idx
  on public.perfil_psi_clinico (psi_user_id);

alter table public.perfil_psi_clinico enable row level security;
grant select, insert, update on public.perfil_psi_clinico to authenticated;

drop policy if exists "perfil_psi_select_own" on public.perfil_psi_clinico;
create policy "perfil_psi_select_own"
on public.perfil_psi_clinico for select to authenticated
using (psi_user_id = auth.uid());

drop policy if exists "perfil_psi_insert_own" on public.perfil_psi_clinico;
create policy "perfil_psi_insert_own"
on public.perfil_psi_clinico for insert to authenticated
with check (psi_user_id = auth.uid());

drop policy if exists "perfil_psi_update_own" on public.perfil_psi_clinico;
create policy "perfil_psi_update_own"
on public.perfil_psi_clinico for update to authenticated
using (psi_user_id = auth.uid())
with check (psi_user_id = auth.uid());

create table if not exists public.alertas_ativacao (
  id bigint generated by default as identity primary key,
  psi_user_id uuid not null references public.psis(user_id) on delete cascade,
  paciente_nome text not null,
  paciente_ref_id text,
  mecanismo text not null check (mecanismo in (
    'ressonancia_esquema',
    'complementaridade_modo',
    'gatilho_tema'
  )),
  nivel text not null check (nivel in ('moderado', 'alto', 'critico')),
  score numeric(5,2),
  esquemas_em_ressonancia text[],
  modos_complementares text[],
  temas_inferidos text[],
  temas_confirmados_psi text[],
  temas_confirmados_em timestamptz,
  titulo_alerta text not null,
  texto_alerta text not null,
  sugestao_clinica text,
  referencias text[],
  n_ocorrencias integer not null default 1,
  primeira_vez_em timestamptz not null default now(),
  ultima_vez_em timestamptz not null default now(),
  lido_em timestamptz,
  arquivado boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists alertas_psi_user_id_idx
  on public.alertas_ativacao (psi_user_id, arquivado, created_at desc);
create index if not exists alertas_paciente_idx
  on public.alertas_ativacao (psi_user_id, paciente_nome);

-- Garante deduplicacao real para o ON CONFLICT do trigger.
create unique index if not exists alertas_ativacao_dedupe_idx
  on public.alertas_ativacao (
    psi_user_id,
    paciente_nome,
    mecanismo,
    coalesce(titulo_alerta, '')
  );

alter table public.alertas_ativacao enable row level security;
grant select, update on public.alertas_ativacao to authenticated;

drop policy if exists "alertas_select_own" on public.alertas_ativacao;
create policy "alertas_select_own"
on public.alertas_ativacao for select to authenticated
using (psi_user_id = auth.uid());

drop policy if exists "alertas_update_own" on public.alertas_ativacao;
create policy "alertas_update_own"
on public.alertas_ativacao for update to authenticated
using (psi_user_id = auth.uid())
with check (psi_user_id = auth.uid());

create table if not exists public.matriz_complementaridade (
  id bigint generated by default as identity primary key,
  modo_paciente text not null,
  modo_psi text not null,
  nivel_risco text not null check (nivel_risco in ('alto', 'moderado', 'baixo')),
  descricao_risco text not null,
  sugestao_observacao text not null,
  fonte text default 'Arntz & Jacob (2012)',
  created_at timestamptz not null default now()
);

create unique index if not exists matriz_complementaridade_pair_idx
  on public.matriz_complementaridade (modo_paciente, modo_psi);

alter table public.matriz_complementaridade enable row level security;
grant select on public.matriz_complementaridade to authenticated;

drop policy if exists "matriz_select_all" on public.matriz_complementaridade;
create policy "matriz_select_all"
on public.matriz_complementaridade for select to authenticated
using (true);

create table if not exists public.temas_clinicos (
  id bigint generated by default as identity primary key,
  tema_id text unique not null,
  tema_label text not null,
  esquemas_assoc text[] not null,
  modos_assoc text[],
  itens_ysq integer[],
  itens_smi integer[],
  created_at timestamptz not null default now()
);

alter table public.temas_clinicos enable row level security;
grant select on public.temas_clinicos to authenticated;

drop policy if exists "temas_select_all" on public.temas_clinicos;
create policy "temas_select_all"
on public.temas_clinicos for select to authenticated
using (true);

create or replace function public.fn_calcular_ativacao(
  p_psi_user_id uuid,
  p_paciente_nome text
)
returns table (
  mecanismo text,
  nivel text,
  score numeric,
  titulo text,
  texto text,
  sugestao text,
  elementos text[],
  referencias text[]
)
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_ysq_psi jsonb;
  v_smi_psi jsonb;
  v_ysq_paciente jsonb;
  v_smi_paciente jsonb;
  v_n_preench integer;
  v_esquema text;
  v_score_psi numeric;
  v_score_pac numeric;
  v_delta numeric;
  v_peso numeric;
  v_res numeric;
  v_soma_res numeric := 0;
  v_count_res integer := 0;
  v_esquemas_res text[] := '{}';
  v_modo_pac text;
  v_score_modo_pac numeric;
  v_nivel text;
  v_score_final numeric;
  v_esquemas text[] := ARRAY[
    'abandono','desconfianca_abuso','privacao_emocional','defectividade',
    'isolamento_social','dependencia','vulnerabilidade_dano','emaranhamento',
    'fracasso','arrogo','autocontrole_insuf','subjugacao','autossacrificio',
    'busca_aprovacao','negativismo','inibicao_emocional','padroes_inflexiveis',
    'postura_punitiva'
  ];
begin
  -- Impede que uma psi consulte dados derivados de outra psi.
  if auth.uid() is null or p_psi_user_id <> auth.uid() then
    raise exception 'forbidden';
  end if;

  select ysq_scores, smi_scores, n_preenchimentos
  into v_ysq_psi, v_smi_psi, v_n_preench
  from public.perfil_psi_clinico
  where psi_user_id = p_psi_user_id;

  if v_ysq_psi is null then
    return;
  end if;

  select rc.scores
  into v_ysq_paciente
  from public.respostas_clinicas rc
  where rc.psi_user_id = p_psi_user_id
    and rc.paciente_nome ilike p_paciente_nome
    and rc.formulario = 'YSQ-S3'
  order by rc.criado_em desc
  limit 1;

  select rs.scores_modos
  into v_smi_paciente
  from public.respostas_smi rs
  where rs.psi_user_id = p_psi_user_id
    and rs.paciente_nome ilike p_paciente_nome
  order by rs.criado_em desc
  limit 1;

  if v_ysq_paciente is not null then
    foreach v_esquema in array v_esquemas loop
      v_score_psi := coalesce((v_ysq_psi ->> v_esquema)::numeric, 0);
      v_score_pac := coalesce((v_ysq_paciente ->> v_esquema)::numeric, 0);

      if v_score_psi >= 4.0 and v_score_pac >= 4.0 then
        v_delta := abs(v_score_psi - v_score_pac);
        v_peso := (v_score_psi + v_score_pac) / 2.0;
        v_res := v_peso * (1.0 - v_delta / 6.0);
        v_soma_res := v_soma_res + v_res;
        v_count_res := v_count_res + 1;
        v_esquemas_res := v_esquemas_res || v_esquema;
      end if;
    end loop;

    if v_count_res > 0 then
      v_score_final := round((v_soma_res / v_count_res) * 100.0 / 6.0, 1);
      if v_n_preench >= 3 then
        v_score_final := least(v_score_final * 1.1, 100);
      end if;

      v_peso := v_soma_res / v_count_res;
      if v_peso > 5.0 then
        v_nivel := 'critico';
      elsif v_peso >= 4.5 then
        v_nivel := 'alto';
      else
        v_nivel := 'moderado';
      end if;

      return query select
        'ressonancia_esquema',
        v_nivel,
        v_score_final,
        format('Possivel ressonancia de esquema - %s (%s/100)',
          initcap(replace(v_esquemas_res[1], '_', ' ')),
          v_score_final::text),
        format(
          'Os esquemas %s aparecem ativados tanto no seu perfil quanto nos resultados de %s. Quando esses temas emergirem em sessao, observe sua resposta interna - pode haver risco de validacao mutua inconsciente em vez de intervencao clinica.',
          array_to_string(v_esquemas_res, ', '),
          p_paciente_nome
        ),
        'Verifique se ha dificuldade de confrontar esses padroes neste paciente. A ressonancia de esquema nao impede o trabalho clinico; ela pede atencao adicional.',
        v_esquemas_res,
        ARRAY['Young, Klosko & Weishaar (2003) cap. 11', 'Ligiero & Gelso (2002)', 'Hayes et al. (2011)'];
    end if;
  end if;

  if v_smi_paciente is not null then
    for v_modo_pac, v_score_modo_pac in
      select key, value::numeric
      from jsonb_each_text(v_smi_paciente)
      where value::numeric >= 4.0
      order by value::numeric desc
    loop
      return query
      select
        'complementaridade_modo',
        case
          when m.nivel_risco = 'alto'
            and coalesce((v_smi_psi ->> m.modo_psi)::numeric, 0) >= 4.5 then 'critico'
          when m.nivel_risco = 'alto' then 'alto'
          else 'moderado'
        end,
        round(
          coalesce((v_smi_psi ->> m.modo_psi)::numeric, 0)
          * v_score_modo_pac / 6.0 * 100.0 / 6.0,
          1
        ),
        format('Hipotese: modo %s (paciente) x modo %s (voce)',
          initcap(replace(v_modo_pac, '_', ' ')),
          initcap(replace(m.modo_psi, '_', ' '))),
        m.descricao_risco,
        m.sugestao_observacao,
        ARRAY[v_modo_pac, m.modo_psi],
        ARRAY[m.fonte]
      from public.matriz_complementaridade m
      where m.modo_paciente = v_modo_pac
        and coalesce((v_smi_psi ->> m.modo_psi)::numeric, 0) >= 4.0;
    end loop;
  end if;

  if v_ysq_paciente is not null then
    return query
    select
      'gatilho_tema',
      'moderado',
      round((
        select avg(coalesce((v_ysq_psi ->> s.esquema)::numeric, 0))
        from unnest(t.esquemas_assoc) as s(esquema)
      ) * 100.0 / 6.0, 1),
      format('Temas provaveis da sessao com %s', p_paciente_nome),
      format(
        'Com base nos instrumentos disponiveis, os temas "%s" tem maior probabilidade de emergir e de ativar seus esquemas. Estes sao temas sugeridos - confirme, remova ou adicione conforme seu conhecimento clinico do paciente.',
        t.tema_label
      ),
      'Prepare-se para observar sua resposta interna quando esses temas aparecerem. Essa preparacao previa e uma estrategia importante de manejo da contratransferencia.',
      t.esquemas_assoc || coalesce(t.modos_assoc, '{}'),
      ARRAY['Hayes et al. (2011)', 'Gelso (2014)']
    from public.temas_clinicos t
    where exists (
      select 1
      from unnest(t.esquemas_assoc) as s(esquema)
      where coalesce((v_ysq_psi ->> s.esquema)::numeric, 0) >= 4.0
        and coalesce((v_ysq_paciente ->> s.esquema)::numeric, 0) >= 4.0
    )
    order by t.tema_label
    limit 4;
  end if;
end;
$function$;

revoke all on function public.fn_calcular_ativacao(uuid, text) from public;
grant execute on function public.fn_calcular_ativacao(uuid, text) to authenticated;

create or replace function public.trg_gerar_alertas_ativacao()
returns trigger
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_psi_id uuid;
  v_pac_nome text;
  v_alerta record;
begin
  if TG_TABLE_NAME = 'respostas_clinicas' then
    v_psi_id := NEW.psi_user_id;
    v_pac_nome := NEW.paciente_nome;
  elsif TG_TABLE_NAME = 'respostas_smi' then
    v_psi_id := NEW.psi_user_id;
    v_pac_nome := NEW.paciente_nome;
  end if;

  if v_psi_id is null or v_pac_nome is null then
    return NEW;
  end if;

  if not exists (
    select 1 from public.perfil_psi_clinico where psi_user_id = v_psi_id
  ) then
    return NEW;
  end if;

  for v_alerta in
    select * from public.fn_calcular_ativacao(v_psi_id, v_pac_nome)
  loop
    insert into public.alertas_ativacao (
      psi_user_id, paciente_nome, paciente_ref_id,
      mecanismo, nivel, score,
      esquemas_em_ressonancia, modos_complementares, temas_inferidos,
      titulo_alerta, texto_alerta, sugestao_clinica, referencias,
      n_ocorrencias, ultima_vez_em
    )
    values (
      v_psi_id, v_pac_nome, NEW.id::text,
      v_alerta.mecanismo, v_alerta.nivel, v_alerta.score,
      case when v_alerta.mecanismo = 'ressonancia_esquema' then v_alerta.elementos end,
      case when v_alerta.mecanismo = 'complementaridade_modo' then v_alerta.elementos end,
      case when v_alerta.mecanismo = 'gatilho_tema' then v_alerta.elementos end,
      v_alerta.titulo, v_alerta.texto, v_alerta.sugestao, v_alerta.referencias,
      1, now()
    )
    on conflict (
      psi_user_id,
      paciente_nome,
      mecanismo,
      coalesce(titulo_alerta, '')
    )
    do update set
      nivel = excluded.nivel,
      score = excluded.score,
      texto_alerta = excluded.texto_alerta,
      sugestao_clinica = excluded.sugestao_clinica,
      referencias = excluded.referencias,
      n_ocorrencias = public.alertas_ativacao.n_ocorrencias + 1,
      ultima_vez_em = now(),
      arquivado = false;
  end loop;

  return NEW;
end;
$function$;

drop trigger if exists trg_ativacao_ysq on public.respostas_clinicas;
create trigger trg_ativacao_ysq
after insert on public.respostas_clinicas
for each row execute function public.trg_gerar_alertas_ativacao();

-- Este trigger depende da tabela respostas_smi existir no arquivo psireal_smi_supabase.sql.
drop trigger if exists trg_ativacao_smi on public.respostas_smi;
create trigger trg_ativacao_smi
after insert on public.respostas_smi
for each row execute function public.trg_gerar_alertas_ativacao();

create or replace view public.v_alertas_ativos as
select
  a.id,
  a.psi_user_id,
  a.paciente_nome,
  a.mecanismo,
  a.nivel,
  a.score,
  a.titulo_alerta,
  a.texto_alerta,
  a.sugestao_clinica,
  a.esquemas_em_ressonancia,
  a.modos_complementares,
  a.temas_inferidos,
  a.temas_confirmados_psi,
  a.referencias,
  a.n_ocorrencias,
  a.lido_em,
  a.ultima_vez_em,
  case a.nivel
    when 'critico' then 3
    when 'alto' then 2
    when 'moderado' then 1
  end + least(a.n_ocorrencias, 5) as prioridade
from public.alertas_ativacao a
where a.arquivado = false
  and a.psi_user_id = auth.uid();

grant select on public.v_alertas_ativos to authenticated;
