-- Psi Real public contact forms.
-- Safe to run even if the contatos table already exists.

create table if not exists public.contatos (
  id bigint generated by default as identity primary key
);

alter table public.contatos
  add column if not exists nome text,
  add column if not exists whatsapp text,
  add column if not exists servico text,
  add column if not exists mensagem text,
  add column if not exists pagina text,
  add column if not exists status text default 'novo',
  add column if not exists created_at timestamptz default now();

alter table public.contatos enable row level security;

grant usage on schema public to anon, authenticated;
grant insert on public.contatos to anon, authenticated;

drop policy if exists "public_insert_contatos" on public.contatos;
create policy "public_insert_contatos"
on public.contatos
for insert
to anon, authenticated
with check (true);

create index if not exists contatos_created_at_idx
on public.contatos (created_at desc);
