-- ============================================================
-- PSIREAL — SMI + BIBLIOTECA TE
-- Execute após psireal_supabase_migration_FINAL.sql
-- ============================================================

-- Tabela de formulários SMI respondidos pelos pacientes
create table if not exists public.respostas_smi (
  id                  bigint generated by default as identity primary key,
  psi_user_id         uuid not null references public.psis(user_id) on delete cascade,
  patient_link_id     uuid references public.patient_links(id) on delete set null,
  paciente_nome       text not null,
  paciente_nascimento date,

  -- Respostas brutas (JSON: {"1": 3, "2": 5, ...})
  respostas           jsonb not null,

  -- Scores por modo (média de cada subescala)
  scores_modos        jsonb,
  -- Ex: {"crianca_vulneravel": 4.2, "pai_punitivo": 3.8, "adulto_saudavel": 2.1, ...}

  -- Scores por domínio (média dos modos do domínio)
  scores_dominios     jsonb,
  -- Ex: {"crianca": 3.5, "enfrentamento": 2.8, "hipercompensador": 1.9, "pais": 4.1, "adulto_saudavel": 2.1}

  -- Modo mais ativado (calculado no backend)
  modo_predominante   text,
  -- Combinações críticas identificadas
  alertas_clinicos    jsonb,
  -- Ex: [{"combinacao": "CV+PD", "nivel": "alto", "descricao": "..."}]

  -- Cruzamento com YSQ (se disponível)
  cruzamento_ysq      jsonb,
  -- Ex: {"dominio_ysq": "Desconexão", "esquemas_ativos": ["Abandono", "Privação"], "modos_esperados": [...], "consistente": true}

  notas_psi           text,
  status              text not null default 'novo',
  psi_id              text,  -- legado: slug
  criado_em           timestamptz,
  created_at          timestamptz not null default now()
);

create index if not exists respostas_smi_psi_user_id_idx on public.respostas_smi (psi_user_id);
create index if not exists respostas_smi_created_at_idx  on public.respostas_smi (created_at desc);

-- Trigger legado (mesmo padrão do respostas_clinicas)
create or replace function public.sync_respostas_smi_legado()
returns trigger language plpgsql as $$
begin
  if NEW.criado_em is null then NEW.criado_em := NEW.created_at; end if;
  if NEW.psi_id is null and NEW.psi_user_id is not null then
    select psi_id into NEW.psi_id from public.psis where user_id = NEW.psi_user_id;
  end if;
  return NEW;
end;
$$;

drop trigger if exists trg_sync_smi_legado on public.respostas_smi;
create trigger trg_sync_smi_legado
before insert or update on public.respostas_smi
for each row execute function public.sync_respostas_smi_legado();

-- RLS
alter table public.respostas_smi enable row level security;
grant select, update on public.respostas_smi to authenticated;

drop policy if exists "smi_select_own" on public.respostas_smi;
create policy "smi_select_own"
on public.respostas_smi for select to authenticated
using (psi_user_id = auth.uid());

drop policy if exists "smi_update_own" on public.respostas_smi;
create policy "smi_update_own"
on public.respostas_smi for update to authenticated
using (psi_user_id = auth.uid())
with check (psi_user_id = auth.uid());

-- ============================================================
-- BIBLIOTECA DE LITERATURA (conteúdo estático da plataforma)
-- Acessível por qualquer psi autenticada
-- ============================================================

create table if not exists public.biblioteca_te (
  id          bigint generated by default as identity primary key,
  ref_id      text unique not null,  -- ex: 'young2003', 'lobbestael2010'
  categoria   text not null,
  cor         text not null,
  autores     text not null,
  ano         integer not null,
  titulo      text not null,
  subtitulo   text,
  tipo        text default 'livro',  -- livro, artigo, dissertacao, capitulo
  periodico   text,
  editora     text,
  local_pub   text,
  volume      text,
  numero      text,
  paginas     text,
  doi         text,
  instituicao text,
  resumo      text not null,
  tags        text[],
  destaque    boolean default false,
  created_at  timestamptz not null default now()
);

alter table public.biblioteca_te enable row level security;
grant select on public.biblioteca_te to authenticated;

drop policy if exists "biblioteca_select_all" on public.biblioteca_te;
create policy "biblioteca_select_all"
on public.biblioteca_te for select to authenticated
using (true);

-- ============================================================
-- REGRAS DE ATIVAÇÃO (cruzamento YSQ × SMI)
-- ============================================================

create table if not exists public.regras_ativacao (
  id                  bigint generated by default as identity primary key,
  dominio_ysq         text not null,
  esquemas            text[] not null,
  modos_primarios     text[] not null,
  modos_secundarios   text[],
  descricao           text not null,
  implicacao_clinica  text,
  nivel_alerta        text not null default 'moderado',
  fonte               text default 'Young, Klosko & Weishaar (2003)',
  created_at          timestamptz not null default now()
);

alter table public.regras_ativacao enable row level security;
grant select on public.regras_ativacao to authenticated;

drop policy if exists "regras_select_all" on public.regras_ativacao;
create policy "regras_select_all"
on public.regras_ativacao for select to authenticated
using (true);

-- Inserir regras de ativação baseadas em Young (2003)
insert into public.regras_ativacao
  (dominio_ysq, esquemas, modos_primarios, modos_secundarios, descricao, implicacao_clinica, nivel_alerta)
values
  (
    'Desconexão e Rejeição',
    ARRAY['Abandono', 'Desconfiança/Abuso', 'Privação Emocional', 'Defectividade', 'Isolamento Social'],
    ARRAY['Criança Vulnerável', 'Pai/Mãe Punitivo(a)'],
    ARRAY['Protetor Desligado', 'Capitulador Complacente'],
    'Esquemas de desconexão ativam vulnerabilidade emocional intensa e autocrítica severa. Como enfrentamento, frequentemente surgem evitação emocional ou submissão.',
    'Priorizar segurança terapêutica e reparentalidade limitada antes de técnicas cognitivas. O ciclo vergonha-evitação é o alvo central.',
    'alto'
  ),
  (
    'Autonomia e Desempenho Prejudicados',
    ARRAY['Dependência', 'Vulnerabilidade ao Dano', 'Emaranhamento', 'Fracasso'],
    ARRAY['Criança Vulnerável', 'Capitulador Complacente'],
    ARRAY['Protetor Desligado'],
    'Esquemas de autonomia prejudicada ativam dependência emocional e dificuldade de agir de forma independente.',
    'Trabalhar autonomia gradual com psicoeducação sobre necessidades emocionais. Técnicas de imagery para fortalecer o Adulto Saudável.',
    'moderado'
  ),
  (
    'Limites Prejudicados',
    ARRAY['Arrogo/Grandiosidade', 'Autocontrole Insuficiente'],
    ARRAY['Criança Impulsiva', 'Autoengrandecedor', 'Criança Raivosa'],
    ARRAY['Intimidação e Ataque'],
    'Esquemas de limites prejudicados ativam impulsividade e desconsideração dos outros. Em frustração, emergem raiva e dominação.',
    'Regulação emocional prioritária. Mindfulness, pausas antes de resposta impulsiva. Diálogo de modos para fortalecer o Adulto Saudável como mediador.',
    'alto'
  ),
  (
    'Orientação para o Outro',
    ARRAY['Subjugação', 'Autossacrifício', 'Busca de Aprovação'],
    ARRAY['Capitulador Complacente', 'Pai/Mãe Exigente/Crítico(a)'],
    ARRAY['Autoconfortador Desligado', 'Criança Vulnerável'],
    'Esquemas de orientação ao outro ativam supressão das próprias necessidades e exigência interna por aprovação constante.',
    'Identificar necessidades não atendidas. Assertividade e autocompaixão como alvos. Atenção ao risco de burnout e comportamentos autoconsoladores.',
    'moderado'
  ),
  (
    'Supervigilância e Inibição',
    ARRAY['Negativismo', 'Inibição Emocional', 'Padrões Inflexíveis', 'Postura Punitiva'],
    ARRAY['Pai/Mãe Punitivo(a)', 'Pai/Mãe Exigente/Crítico(a)'],
    ARRAY['Protetor Desligado', 'Criança Vulnerável'],
    'Esquemas de supervigilância ativam exigência interna rígida e punição por erros. O Protetor Desligado pode emergir para evitar o sofrimento causado pelos modos críticos.',
    'Trabalho com imagery de reparentalidade para enfraquecer os modos punitivos. Autocompaixão como antídoto ao Pai Punitivo.',
    'moderado'
  )
on conflict do nothing;

-- ============================================================
-- RPC: submit_smi_response
-- Paciente envia respostas do SMI via token
-- ============================================================
create or replace function public.submit_smi_response(
  p_token             uuid,
  p_patient_name      text,
  p_patient_birth     date,
  p_respostas         jsonb,
  p_scores_modos      jsonb,
  p_scores_dominios   jsonb,
  p_modo_predominante text,
  p_alertas_clinicos  jsonb default null
)
returns void language plpgsql security definer set search_path = public
as $$
declare
  v_link  public.patient_links%rowtype;
  v_psi_id text;
begin
  select * into v_link
  from public.patient_links
  where token = p_token
    and instrumento = 'SMI'
    and status = 'ativo'
    and (expires_at is null or expires_at > now())
  limit 1;

  if v_link.id is null then
    raise exception 'link inválido ou expirado';
  end if;

  select psi_id into v_psi_id from public.psis where user_id = v_link.psi_user_id;

  insert into public.respostas_smi (
    psi_user_id, patient_link_id,
    paciente_nome, paciente_nascimento,
    respostas, scores_modos, scores_dominios,
    modo_predominante, alertas_clinicos,
    psi_id, criado_em, status, created_at
  ) values (
    v_link.psi_user_id, v_link.id,
    coalesce(nullif(trim(p_patient_name), ''), v_link.patient_name),
    coalesce(p_patient_birth, v_link.patient_birth),
    p_respostas, p_scores_modos, p_scores_dominios,
    p_modo_predominante, p_alertas_clinicos,
    v_psi_id, now(), 'novo', now()
  );

  update public.patient_links set status = 'respondido' where id = v_link.id;
end;
$$;

revoke all on function public.submit_smi_response(uuid,text,date,jsonb,jsonb,jsonb,text,jsonb) from public;
grant execute on function public.submit_smi_response(uuid,text,date,jsonb,jsonb,jsonb,text,jsonb) to anon, authenticated;
